Update install-oracle-11g

diff --git a/kubuntu/install-oracle-11g b/kubuntu/install-oracle-11g
--- a/kubuntu/install-oracle-11g
+++ b/kubuntu/install-oracle-11g
@@ -7,7 +7,61 @@ Step-by-step install oracle 11g in Ubuntu
 # mv Disk1/ /opt/oracle/
 # cd /opt/oracle/
 # sudo alien --scripts -d oracle-xe-11.2.0-1.0.x86_64.rpm (generate ke format deb, tunggu beberapa saat)
-# 
+# sudo pico /sbin/chkconfig
+# copy paste :
+-----------------------------------------------------------
+    #!/bin/bash
+    # Oracle 11gR2 XE installer chkconfig hack for Ubuntu
+      file=/etc/init.d/oracle-xe
+      if [[ ! `tail -n1 $file | grep INIT` ]]; then
+          echo >> $file
+          echo '### BEGIN INIT INFO' >> $file
+          echo '# Provides: OracleXE' >> $file
+          echo '# Required-Start: $remote_fs $syslog' >> $file
+          echo '# Required-Stop: $remote_fs $syslog' >> $file
+          echo '# Default-Start: 2 3 4 5' >> $file
+          echo '# Default-Stop: 0 1 6' >> $file
+          echo '# Short-Description: Oracle 11g Express Edition' >> $file
+          echo '### END INIT INFO' >> $file
+      fi
+      update-rc.d oracle-xe defaults 80 01
+-----------------------------------------------------------
+# sudo chmod 755 /sbin/chkconfig  
+# sudo pico /etc/sysctl.d/60-oracle.conf
+# copy paste :
+-----------------------------------------------------------
+    # Oracle 11g XE kernel parameters 
+    fs.file-max=6815744  
+    net.ipv4.ip_local_port_range=9000 65000  
+    kernel.sem=250 32000 100 128 
+    kernel.shmmax=536870912 
+-----------------------------------------------------------
+# sudo cat /etc/sysctl.d/60-oracle.conf 
+# sudo service procps start
+# sudo sysctl -q fs.file-max
+# sudo pico /etc/rc2.d/S01shm_load
+# copy paste :
+-----------------------------------------------------------
+    #!/bin/sh
+    case "$1" in
+    start)
+        mkdir /var/lock/subsys 2>/dev/null
+        touch /var/lock/subsys/listener
+        rm /dev/shm 2>/dev/null
+        mkdir /dev/shm 2>/dev/null
+    *)
+        echo error
+        exit 1
+        ;;
+
+    esac 
+-----------------------------------------------------------
+# sudo ln -s /usr/bin/awk /bin/awk 
+# sudo mkdir /var/lock/subsys 
+# sudo touch /var/lock/subsys/listener
+
+# Now, Reboot Your System!
+
 
 
 Referensi : 
